
module.exports = {
    
    access_token: 'EAACubcIenBMBAPowfDB26LzYTWsrQyLnqxzAZCSdXyX0cI5dKxoaZBL5Wx7Rsv4nwafpbEgwMnlXmXx38VJgyBIOSIWZAYWCCvYrnAsNYJ4k9UakM62RSPVzqfNkEr9hzLm1krlRsrRnWMipF9ffZC3I9GzbkPa3tFwZC2szib5EHbFPsLDIaNa8AB8oADDwZD'
}
